name: GitHub CI Test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # VERSION: XiaoleiShi-NV-ci_test

jobs:
  build:
    runs-on: self-hosted

    container: 
      image: xiaoleishi/hugectr:v1.1
      volumes: 
        - /home/hugectr/actions-runner/dataset:/dataset

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build single node 
        working-directory: ${{runner.workspace}}/HugeCTR
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DSM=70 .. && make -j

      - name: Unit test
        working-directory: ${{runner.workspace}}/HugeCTR/build/bin
        shell: bash
        run: |
          ./layers_test
          ./embedding_test
          ./checker_test
          ./data_parser_test
          ./data_reader_test
          ./device_map_test
          ./heap_test
          ./loss_test
          ./optimizer_test
          ./regularizers_test
          ./parser_test
          ./session_test

